### ISSUE TITLE
Version naming scheme

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/gimie#34]
The current release of gimie is named `v0.2.0`, but the docker image tags in #31 are named based on the version in `pyproject.toml`, which is now `0.2.0`.
Would it make sense to drop the `v` from releases or should we prepend the v to docker tags?

> Note: On PyPI the package should probably be named `0.2.0` as `v0.2.0` is not [semver](https://semver.org/) compliant

**Comment by caviri** [comment]
Personally, I prefer to avoid prepending `v` to versions. It is not semver 2.0 compliant: 

https://semver.org/

> Is “v1.2.3” a semantic version?
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

**Comment by cmdoret** [comment]
:ok_hand: the `v` is going away
