### ISSUE TITLE
[gimie] github properties beyond codemetapy

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/gimie#39]
Git providers (Gitlab, Github, Codeberg, ...) provide additional useful information with no corresponding codemeta property. Namely:
* Where the repository is forked from
* How many forks the repository has
* How many stars the repository has

Would it make sense to add such properties, for example using schema.org terms. One example that come to mind would be to use schema:isBasedOn for forks:

```
<downstream-repo> schema:isBasedOn <upstream-repo>
```

For stars, maybe [schema:InteractionStatistic](https://schema.org/interactionStatistic) ? But that seems a bit convoluted.

Would love to hear your suggestions @rmfranken

**Comment by rmfranken** [comment]
Realized today that github does not correctly notify me when tagged... isBasedOn seems very appropriate for forks indeed. number of forks or stars does not exist as a schema.org property. For stars: https://schema.org/membershipPointsEarned Is pretty close, and it does mention "stars" as one of the potential units. Number of forks is harder. I'll keep searching. :)

**Comment by cmdoret** [comment]
Isn't `schema:membershipPointsEarned` a `Person`-bound property rather than Project-bound? The description says: _The number of membership points earned by the member_

Knowing where a project is forked from is probably the most important anyways. Having platform-independent statistics is nice to have, but more superficial. Maybe I can create a separate issue to keep this in mind for later?

**Comment by rmfranken** [comment]
Yeah, you are right, I mis-read it. Perhaps we can make our own properties for #forks and #stars, which we define well and attribute to a softwareSourceCode. It would not be a lot of work, but I agree its not as nice as re-using something pre-existing.

**Comment by rmfranken** [comment]
I propose to put "is based on" as a separate ticket, and then close this one so we keep our issuelist clean. In the spirit of asking for forgiveness rather than permission I will do so :)
