### ISSUE TITLE
Extract license when unavailable

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/gimie#67]
Currently, gimie only retrieves the license from the GitHub API.
The GitLab API does not provide license at all, and the GitHub API license detection is lacking and will return NOASSERTION when:

* the license is in a different file (e.g. LICENSE.md)
* multiple licenses are found in the repo
* the license is slightly different (e.g. added copyright notice)
* the license is not one of the most popular licenses

For cases when gimie fails to retrieve a license from the Git provider, it would be preferable to extract it locally. The process could look as follows:

```mermaid
graph TD;
    query[Send API request to git provider] -->check[license in response?];
    check -->|yes| return[Success];
    check -->|no| clone[Clone repository];
    clone --> extract[Locally extract license];
    extract --> add[Add to graph];
    add --> return
```

This would add considerable overhead only in cases when license cannot be determined from the provider. This approach could also be applied to other attributes that may be missing from the API but present in the repo.

**Comment by rmfranken** [comment]
Gitlab blobs? for accessing the tree (?)

We want to use our existing license extractor and matcher on the tree structure - without cloning the repository. 

IF this is fast, we can make it default and bypass the API's.

**Comment by rmfranken** [comment]
I will give a try for this - specifically for the GitHub variant first. If that works, I'll move to GitLab.

**Comment by cmdoret** [comment]
WIP
* Pre-requisite in #70 
* implementation in #68
