### ISSUE TITLE
Fix docker push CI

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/gimie#74]
the docker build and push CI workflow fails with:

```
#24 2.746 OSError: libgomp.so.1: cannot open shared object file: No such file or directory
```

**Objective:** Fix CI

**Requirements:**

* [x] Investigate issue in logs
* [x] Update Dockerfile as required
* [ ] Trigger image push

**Comment by supermaxiste** [comment]
Source of the issue from [here](https://stackoverflow.com/questions/70183074/oserror-libgomp-so-1-not-found-when-importing-gluoncv-through-azure-app-service). For the last point, I can't trigger the push myself.

**Comment by supermaxiste** [comment]
Looks like there's an OS incompatibility issue:
```
Unable to find installation candidates for typecode-libmagic (5.39.210531)
```
Next steps:

- [ ] Check alternative options to keep `arm64` architecture
- [ ] If yes to point above: consider if it's worth the effort
- [ ] If no, discuss dropping the architecture or the dependency

**Comment by cmdoret** [comment]
Insights so far: 
* scancode-toolkit ships with typecode-libmagic, a binary python package with an optimized libmagic. It is fast, but not arm64-compatible
* scancode-toolkit-mini does not ship typecode-libmagic and can use the system's libmagic. It works on any platform, but is very slow

**Comment by supermaxiste** [comment]
Shall we can keep the toolkit as is and fix the docker push for this issue?
For optimizing the scancode-toolkit we can open a separate issue, what do you think?
